# infra/charts/autoops/values.yaml
# Default values for autoops.
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: ghcr.io/luca1paul/autoops-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
- name: ghcr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 200m # 0.2 CPU Cores
    memory: 256Mi # 256 Megabytes RAM
  requests:
    cpu: 100m # 0.1 CPU Cores
    memory: 128Mi # 128 Megabytes RAM

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: false
  name: "default"

livenessProbe:
  httpGet:
    path: /status
    port: http
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /status
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Disable autoscaling explicitly to match my template logic
autoscaling:
  enabled: false
