apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autoops.fullname" . }}
  labels:
    {{- include "autoops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "autoops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "autoops.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: {{ include "autoops.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # --- FORCED RESOURCES ---
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          # -------------------------
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10